### ISSUE TITLE
i can't figure out how to use this at all

### ISSUE THREAD

**Issue by SArpnt** [ajskateboarder/scratch-git#54]
when i start up turbowarp i get a popup to open an existing project, i can do that but the next button stays greyed out and does nothing. if i close it to make a new project i can't find any way to save it to create a git repository, or any git related menu.

the readme doesn't have any written information on how to build or use this program, and i'm not really sure how it's supposed to work from the video; it just looks like you load the zipped project file twice, i'm not even sure where a git repository is involved.

**Comment by ajskateboarder** [comment]
> when i start up turbowarp i get a popup to open an existing project, i can do that but the next button stays greyed out and does nothing. if i close it to make a new project i can't find any way to save it to create a git repository, or any git related menu.

This was fixed on https://github.com/ajskateboarder/scratch-git/commit/4aa016522861dcd961ffcc6976e33e5d9a4e82a7, but keeping this open until merged. Once you can hit Next, you should be able to enter the project location (this is not available in TurboWarp so a second input is necessary)  and your name/email for Git

> and i'm not really sure how it's supposed to work from the video; it just looks like you load the zipped project file twice, i'm not even sure where a git repository is involved.

I've been intending on updating the video since it's very outdated. Rest assured, this does use your system's git for making commits, diffing, pushing, etc.
